function ds = fcn_2021_11_10(path_csv)
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Volumes/GoogleDrive/My Drive/data/AGROSOFC DataSources/IV_SOFCMAN_202103_share/SPS_IV/202103_SOFCMAN_Comp04a_07V-OCV_01_800C.csv
%
% Auto-generated by MATLAB on 16-Nov-2021 13:55:21

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 30);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["DateTime", "Datetime", "U_stack_sum_SPS", "T10", "T7", "T9", "T8", "T6", "T3", "T4", "T5", "T1", "T2", "H2_act", "CO_act", "CO2_act", "CH4_act", "O2_act", "N2_act", "Air_01_tar", "H2_tar", "CO2_tar", "CO_tar", "Air_02_tar", "CH4_tar", "N2_tar", "pump_set", "I153", "U153", "U_smooth153"];
opts.VariableTypes = ["datetime", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "DateTime", "InputFormat", "yyyy-MM-dd HH:mm:ss");
opts = setvaropts(opts, "Datetime", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
ds = readtable(path_csv, opts);

end