%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Volumes/GoogleDrive/My Drive/data/AGROSOFC DataSources/Reformer/numbers_new_data.csv
%
% Auto-generated by MATLAB on 08-Nov-2021 16:15:34

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 20);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["steamfuelRatio", "airfuelRatio", "inlet_N2", "inlet_O2", "inlet_CO2", "inlet_H2O", "inlet_Argon", "inlet_C", "inlet_H", "steamcarbon", "oxygencarbon", "Temperatur", "outlet_Ar", "outlet_CH4", "outlet_CO", "outlet_CO2", "outlet_H2", "outlet_H2O", "outlet_N2", "outlet_Csoot"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
reformer = readtable("/Volumes/GoogleDrive/My Drive/data/AGROSOFC DataSources/Reformer/numbers_new_data.csv", opts);

 
%% Clear temporary variables
clear opts
file =     '/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/TimeSeries/AGRO_SOFC/REFORMER/2021_11_08_Sim_Reformer/A001_UniformFormat/output';
file = fullfile(file,'dataset01');
save(file,'reformer')