%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/ModellingAndControl/backend/TimeSeries/AGRO_SOFC/SOFC-REFORMER/2021-03-04-SOFC-REFORMER-Martin/A000_RelatedFiles/ReformerPlusStackData.csv
%
% Auto-generated by MATLAB on 13-Apr-2021 14:45:30

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 67, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = [",", ";"];

% Specify column names and types
opts.VariableNames = ["SC", "OC", "HC", "VarName4", "FuelFlow", "SteamFlow", "ReformerAirFlow", "StackAirFlow", "CatBurnerRequiredAir", "VarName10", "SteamFuelRatiomass", "AirFuelRatiomass", "VarName13", "SteamEvaporatorDuty", "VarName15", "ReformerOutletTemperature", "ReformerHeatOfReaction", "VarName18", "ReformerexitMassAr", "ReformerexitMassCH4", "ReformerexitMassCO", "ReformerexitMassCO2", "ReformerexitMassH2", "ReformerexitMassH2O", "ReformerexitMassN2", "ReformerexitMassCsoot", "VarName27", "ReformerexitMolAr", "ReformerexitMolCH4", "ReformerexitMolCO", "ReformerexitMolCO2", "ReformerexitMolH2", "ReformerexitMolH2O", "ReformerexitMolN2", "ReformerexitMolCsoot", "VarName36", "VarName37", "VarName38", "VarName39", "OperatingTemperature", "currentPerStack", "Powerelectrical", "FuelCellHeat", "FuelCellHeat_per", "OxygenUtilization", "massRatio", "fuelFlowBeforeReformer", "VarName48", "CellexitMassAr", "CellexitMassCH4", "CellexitMassCO", "CellexitMassCO2", "CellexitMassH2", "CellexitMassH2O", "CellexitMassN2", "CellexitMassCsoot", "VarName57", "CellexitMolAr", "CellexitMolCH4", "CellexitMolCO", "CellexitMolCO2", "CellexitMolH2", "CellexitMolH2O", "CellexitMolN2", "CellexitMolCsoot", "VarName66", "ExhaustHeatDownTo100C"];
opts.VariableTypes = ["double", "double", "double", "string", "double", "double", "double", "double", "double", "string", "double", "double", "string", "double", "string", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName4", "VarName10", "VarName13", "VarName15", "VarName18", "VarName27", "VarName36", "VarName37", "VarName38", "VarName39", "fuelFlowBeforeReformer", "CellexitMassCsoot", "CellexitMolCsoot"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName4", "VarName10", "VarName13", "VarName15", "VarName18", "VarName27", "VarName36", "VarName37", "VarName38", "VarName39", "fuelFlowBeforeReformer", "CellexitMassCsoot", "CellexitMolCsoot"], "EmptyFieldRule", "auto");

% Import the data
ReformerPlusStackData = readtable("/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/ModellingAndControl/TimeSeries/AGRO_SOFC/SOFC-REFORMER/2021-03-04-SOFC-REFORMER-Martin/A000_RelatedFiles/ReformerPlusStackData.csv", opts);

ReformerPlusStackData = ReformerPlusStackData(10:end,:);
%% Clear temporary variables
ReformerPlusStackData.VarName4  = [];
ReformerPlusStackData.VarName10 = [];
ReformerPlusStackData.VarName18 = [];

ReformerPlusStackData.VarName13 = [];
ReformerPlusStackData.VarName15 = [];
ReformerPlusStackData.VarName27 = [];
ReformerPlusStackData.VarName36 = [];
ReformerPlusStackData.VarName37 = [];
ReformerPlusStackData.VarName38 = [];
ReformerPlusStackData.VarName39 = [];

ReformerPlusStackData.fuelFlowBeforeReformer = [];
%

%
ff = ReformerPlusStackData.VarName48;
ReformerPlusStackData.VarName48 = [];

ReformerPlusStackData.fuelFlowBeforeReformer = ff;
%
ff = ReformerPlusStackData.VarName57;
ReformerPlusStackData.VarName57 = [];
%
ReformerPlusStackData.CellexitMassCsoot = ff;
%
ff = ReformerPlusStackData.VarName66;
ReformerPlusStackData.VarName66 = [];
ReformerPlusStackData.CellexitMolCsoot = ff;

head(ReformerPlusStackData)
save('/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/ModellingAndControl/TimeSeries/AGRO_SOFC/SOFC-REFORMER/2021-03-04-SOFC-REFORMER-Martin/A001_UniformFormat/output/ds.mat','ReformerPlusStackData')

