%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/code/last_data/20220810_20220811_OP_1-4 2/20220810_1130_1333_OP1.csv
%
% Auto-generated by MATLAB on 15-Sep-2022 15:16:57
clear
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 24);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["VarName1", "Datetime", "waterFlowratemlmin", "TIR213C", "TIR2141C", "TIR2143C", "TIR2145C", "TIR2147C", "TIR2149C", "TIR21410C", "TIR21412C", "TIR21414C", "TIR21416C", "TIR21418C", "TIRC215C", "FIRC_2_1mlmin", "FIRC_2_2mlmin", "FIRC_2_3mlmin", "GA_H2_act", "GA_CO_act", "GA_CO2_act", "GA_CH4_act", "GA_O2_act", "SumHCppm"];
opts.VariableTypes = ["double", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "SumHCppm", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "SumHCppm", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Datetime", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
OP1 = readtable("/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/code/last_data/20220810_20220811_OP_1-4 2/20220810_1130_1333_OP1.csv", opts);


%% Clear temporary variables
clear opts

%%
OP1 = OP1(~isnan(OP1.FIRC_2_1mlmin),:);
%%
t = OP1.Datetime;
%
close all
clf
subplot(2,1,1)
hold on
plot(t,OP1.waterFlowratemlmin,'.')
plot(t,OP1.FIRC_2_1mlmin,'.')
subplot(2,1,2)
hold on
plot(t,OP1.GA_CH4_act,'.')
plot(t,OP1.GA_CO2_act,'.')
plot(t,OP1.GA_CO_act,'.')
plot(t,OP1.GA_H2_act,'.')
plot(t,OP1.GA_O2_act,'.')

