%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/code/last_data/20220810_20220811_OP_1-4 2/20220810_1342_1545_OP2.csv
%
% Auto-generated by MATLAB on 15-Sep-2022 15:26:04

%% Set up the Import Options and import the data


%% Clear temporary variables
clear opts

%%
OP1 = OP1(~isnan(OP1.FIRC_2_1mlmin),:);
%%
plot_gr(OP1)


