
clear
%pathfolder = "" + MainPath + 'TimeSeries/AGRO_SOFC/SOFC/2021_02_17_02_Data_UDEUSTO_NN_modified/A000_RelatedFiles/Data_UDEUSTO_NN';
pathfolder = "/Users/djoroya/Google Drive/My Drive/data/AGROSOFC DataSources/SingleCell-Second-Batch/Data_UDEUSTO_NN";
r = dir(pathfolder);
r = r(3:end);
%%
i = 0;
nfiles = length(r');
for ir = r'
    i = i + 1;
    %% Import data from text file
    % Script for importing data from the following text file:
    %
    %    filename: /Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/ModellingAndControl/backend/TimeSeries/AGRO_SOFC/SOFC/2021_02_17_02_Data_UDEUSTO_NN_modified/A000_RelatedFiles/Data_UDEUSTO_NN/20201130_20201213_secondSingleCellTest_Data_UDEUSTO_NN.csv
    %
    % Auto-generated by MATLAB on 15-Mar-2021 11:50:14


    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 25);

    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = "\t";

    % Specify column names and types
    opts.VariableNames = ["VarName1", "DateTime", "Date", "Time", "T_Oven01", "i_act2", "A", "V_act", "v_H2_act", "v_CO_act", "v_CO2_act", "v_CH4_act", "v_O2_act", "v_O2_cath", "H2O_tar", "CH4_tar", "CO2_tar", "H2_tar", "CO_tar", "O2_tar", "N2_tar", "Air_tar", "v_N2_act", "i_real_perA", "i_perA_nC"];
    opts.VariableTypes = ["double", "datetime", "datetime", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Specify variable properties
    opts = setvaropts(opts, "DateTime", "InputFormat", "yyyy-MM-dd HH:mm:ss");
    opts = setvaropts(opts, "Date", "InputFormat", "dd.MM.yyyy");
    opts = setvaropts(opts, "Time", "InputFormat", "HH:mm:ss");

    % Import the data
    secondSingleCellTestDataUDEUSTONN = readtable(pathfolder+"/"+r(i).name, opts);


    %% Clear temporary variables
    clear opts
    
    dataset{i} = secondSingleCellTestDataUDEUSTONN;
    dataset{i}.Date = [];
    dataset{i}.Time = [];
    dataset{i}.VarName1 = [];
    dataset{i} = TableSeries(dataset{i});
    
    %
    fprintf("Table "+i+" of "+nfiles+"\n")

end

%path =     "" + MainPath + 'TimeSeries/AGRO_SOFC/SOFC/2021_02_17_02_Data_UDEUSTO_NN_modified/A001_UniformFormat/output';
path = "/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/TimeSeries/AGRO_SOFC/SOFC/2021_02_17_02_Data_UDEUSTO_NN_modified/A001_UniformFormat/output";
save(fullfile(path,'dataset.mat'),'dataset')
